import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/layouts/Header";
import { AppProvider } from "@/components/AppContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
          <AppProvider>
        <main className="max-w-4xl mx-auto  p-4">
          <Header />
          {children}
          <footer className="mt-16 border-t p-8 text-center text-gray-500">
            &copy; 2024 All rights reserved
          </footer>
        </main>
          </AppProvider>
      </body>
    </html>
  );
}
